"""AstraOS — Real-Time WebSocket Server.

Provides 5 streaming channels with REAL data from the live scanner,
scheduler feed, broker events, and AI signals:

  1. /ws/ticker     — Live market prices (from live_scanner, every 1s)
  2. /ws/signals    — AI research signal updates (from scheduler jobs)
  3. /ws/portfolio  — Portfolio P&L from connected broker(s)
  4. /ws/feed       — Unified event feed (live scanner alerts, news, orders)
  5. /ws/alerts     — Real-time price alerts only (spikes, crashes, breakouts)
"""

import asyncio
import json
from datetime import datetime, timezone
from typing import Any

import structlog  # type: ignore
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query  # type: ignore

logger = structlog.get_logger()

router = APIRouter(tags=["WebSocket Streaming"])


# ═══════════════════════════════════════════════════════════════
# Connection Manager
# ═══════════════════════════════════════════════════════════════

class ConnectionManager:
    """Manages WebSocket connections per channel."""

    def __init__(self):
        self._channels: dict[str, set[WebSocket]] = {}

    async def connect(self, websocket: WebSocket, channel: str):
        await websocket.accept()
        if channel not in self._channels:
            self._channels[channel] = set()
        self._channels[channel].add(websocket)
        logger.info("WS connected", channel=channel, total=len(self._channels[channel]))

    def disconnect(self, websocket: WebSocket, channel: str):
        if channel in self._channels:
            self._channels[channel].discard(websocket)
        logger.info("WS disconnected", channel=channel)

    async def broadcast(self, channel: str, message: dict):
        """Broadcast message to all connections on a channel."""
        dead = []
        for ws in self._channels.get(channel, set()):
            try:
                await ws.send_json(message)
            except Exception:
                dead.append(ws)
        for ws in dead:
            self._channels[channel].discard(ws)

    @property
    def stats(self) -> dict:
        return {ch: len(conns) for ch, conns in self._channels.items()}

    @property
    def total_connections(self) -> int:
        return sum(len(c) for c in self._channels.values())


manager = ConnectionManager()


# ═══════════════════════════════════════════════════════════════
# Channel 1: /ws/ticker — Live Prices (from live_scanner)
# ═══════════════════════════════════════════════════════════════

@router.websocket("/ws/ticker")
async def ws_ticker(
    websocket: WebSocket,
    symbols: str = Query("RELIANCE,TCS,HDFCBANK,INFY,SBIN"),
):
    """Stream live prices from the per-second live scanner.

    Pushes price updates every 1 second with real data from yfinance.
    Subscribe to specific symbols via query param.
    """
    channel = "ticker"
    await manager.connect(websocket, channel)
    symbol_list = [s.strip().upper() for s in symbols.split(",")]

    try:
        while True:
            from ..scheduler.live_scanner import get_live_prices

            all_prices = get_live_prices()
            quotes = []

            for sym in symbol_list:
                # Try exact match, then with .NS suffix
                data = all_prices.get(sym) or all_prices.get(f"{sym}.NS")
                if data:
                    quotes.append(data)
                else:
                    quotes.append({"symbol": sym, "price": 0, "status": "awaiting_scan"})

            await websocket.send_json({
                "type": "ticker",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "quotes": quotes,
                "symbols_tracked": len(all_prices),
            })
            await asyncio.sleep(1)  # 1s refresh — matches scanner frequency

    except WebSocketDisconnect:
        manager.disconnect(websocket, channel)
    except Exception as e:
        logger.error("Ticker WS error", error=str(e))
        manager.disconnect(websocket, channel)


# ═══════════════════════════════════════════════════════════════
# Channel 2: /ws/signals — AI Signal Updates
# ═══════════════════════════════════════════════════════════════

@router.websocket("/ws/signals")
async def ws_signals(websocket: WebSocket):
    """Stream AI research signals as they're generated by the scheduler.

    Pushes new signals every 10 seconds (reads from scheduler job results).
    """
    channel = "signals"
    await manager.connect(websocket, channel)
    last_signal_count = 0

    try:
        while True:
            from ..scheduler.jobs import get_signals, get_signal_history

            signals = get_signals()
            history = get_signal_history()

            # Only push when new signals arrive
            current_count = len(history)
            if current_count > last_signal_count or last_signal_count == 0:
                await websocket.send_json({
                    "type": "signals",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "active_signals": signals,
                    "total_generated": current_count,
                    "new_since_last": current_count - last_signal_count,
                })
                last_signal_count = current_count

            await asyncio.sleep(10)

    except WebSocketDisconnect:
        manager.disconnect(websocket, channel)
    except Exception as e:
        logger.error("Signals WS error", error=str(e))
        manager.disconnect(websocket, channel)


# ═══════════════════════════════════════════════════════════════
# Channel 3: /ws/portfolio — Live Portfolio from Broker
# ═══════════════════════════════════════════════════════════════

@router.websocket("/ws/portfolio")
async def ws_portfolio(websocket: WebSocket, broker: str = Query("paper")):
    """Stream portfolio P&L from the connected broker.

    Reads positions and holdings from the active broker session.
    Updates every 5 seconds.
    """
    channel = "portfolio"
    await manager.connect(websocket, channel)

    try:
        while True:
            from ..routers.broker import _active_sessions

            broker_instance = _active_sessions.get(broker)

            if broker_instance:
                try:
                    positions = await broker_instance.get_positions()
                    funds = await broker_instance.get_funds()

                    total_pnl = sum(getattr(p, "pnl", 0) for p in positions)

                    await websocket.send_json({
                        "type": "portfolio",
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "broker": broker,
                        "positions": [vars(p) for p in positions],
                        "funds": funds,
                        "total_pnl": round(total_pnl, 2),
                        "open_positions": len(positions),
                    })
                except Exception as e:
                    await websocket.send_json({
                        "type": "portfolio_error",
                        "broker": broker,
                        "error": str(e),
                    })
            else:
                # No broker connected — show auto-trader paper trades
                from ..scheduler.auto_trader import get_daily_trades, get_daily_pnl

                await websocket.send_json({
                    "type": "portfolio",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "broker": "auto_trader",
                    "trades_today": get_daily_trades(),
                    "daily_pnl": get_daily_pnl(),
                    "message": f"No broker '{broker}' connected. Showing auto-trader paper trades.",
                })

            await asyncio.sleep(5)

    except WebSocketDisconnect:
        manager.disconnect(websocket, channel)
    except Exception as e:
        logger.error("Portfolio WS error", error=str(e))
        manager.disconnect(websocket, channel)


# ═══════════════════════════════════════════════════════════════
# Channel 4: /ws/feed — Unified Event Feed (REAL)
# ═══════════════════════════════════════════════════════════════

@router.websocket("/ws/feed")
async def ws_feed(websocket: WebSocket):
    """Unified event feed from the scheduler's live intelligence feed.

    Streams real events: market scans, AI signals, news sentiment,
    auto-trade executions, system events, and live scanner alerts.
    Pushes new events as they arrive, checks every 2 seconds.
    """
    channel = "feed"
    await manager.connect(websocket, channel)
    last_seen = 0

    try:
        while True:
            from ..scheduler.engine import get_feed

            feed = get_feed(limit=100)
            current_total = len(feed)

            if current_total > last_seen or last_seen == 0:
                # Send only new events
                new_events = feed[:current_total - last_seen] if last_seen > 0 else feed[:20]

                await websocket.send_json({
                    "type": "feed",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "events": new_events,
                    "total": current_total,
                })
                last_seen = current_total

            await asyncio.sleep(2)

    except WebSocketDisconnect:
        manager.disconnect(websocket, channel)
    except Exception as e:
        logger.error("Feed WS error", error=str(e))
        manager.disconnect(websocket, channel)


# ═══════════════════════════════════════════════════════════════
# Channel 5: /ws/alerts — Real-Time Price Alerts
# ═══════════════════════════════════════════════════════════════

@router.websocket("/ws/alerts")
async def ws_alerts(websocket: WebSocket):
    """Stream real-time price alerts from the live scanner.

    Pushes spike, crash, breakout, and volume surge alerts.
    Checks every 1 second.
    """
    channel = "alerts"
    await manager.connect(websocket, channel)
    last_alert_count = 0

    try:
        while True:
            from ..scheduler.live_scanner import get_alerts, get_scanner_stats

            alerts = get_alerts(limit=20)
            stats = get_scanner_stats()
            current_count = stats.get("alerts_count", 0)

            if current_count > last_alert_count:
                new_alerts = alerts[:current_count - last_alert_count]
                await websocket.send_json({
                    "type": "alerts",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "alerts": new_alerts,
                    "scanner_stats": stats,
                })
                last_alert_count = current_count

            await asyncio.sleep(1)

    except WebSocketDisconnect:
        manager.disconnect(websocket, channel)
    except Exception as e:
        logger.error("Alerts WS error", error=str(e))
        manager.disconnect(websocket, channel)


# ═══════════════════════════════════════════════════════════════
# REST Stats & Broadcast Helpers
# ═══════════════════════════════════════════════════════════════

@router.get("/api/v1/ws/stats")
async def ws_stats():
    """Get current WebSocket connection stats."""
    return {
        "channels": manager.stats,
        "total_connections": manager.total_connections,
        "available_channels": [
            {"path": "/ws/ticker", "description": "Live prices (1s)", "params": "symbols=RELIANCE,TCS"},
            {"path": "/ws/signals", "description": "AI signals (10s)"},
            {"path": "/ws/portfolio", "description": "Portfolio P&L (5s)", "params": "broker=paper"},
            {"path": "/ws/feed", "description": "Event feed (2s)"},
            {"path": "/ws/alerts", "description": "Price alerts (1s)"},
        ],
    }


# ── Broadcast helpers (called by other modules) ──

async def broadcast_signal(signal_data: dict):
    """Broadcast a new AI signal to all /ws/signals subscribers."""
    await manager.broadcast("signals", {
        "type": "signal_update",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "signal": signal_data,
    })


async def broadcast_order_event(order_data: dict):
    """Broadcast an order execution to /ws/feed subscribers."""
    await manager.broadcast("feed", {
        "type": "order",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        **order_data,
    })


async def broadcast_alert(alert_data: dict):
    """Broadcast a price alert to /ws/alerts subscribers."""
    await manager.broadcast("alerts", {
        "type": "alert",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        **alert_data,
    })


async def broadcast_risk_event(risk_data: dict):
    """Broadcast a risk engine event to /ws/feed."""
    await manager.broadcast("feed", {
        "type": "risk",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        **risk_data,
    })
